accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("index/", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("profile/", views.profile, name="profile"),
    path("seller/<str:name>/", views.seller, name="seller"),
    path("follow/<str:name>/", views.follow, name="follow"),
    path("update/", views.update, name="update"),
    path("delete/", views.delete, name="delete"),
    path("nameDuplicate/", views.nameDuplicate, name="nameDuplicate"),
    path("mailDuplicate/", views.mailDuplicate, name="mailDuplicate"),
    path("checkpassword/", views.checkpassword, name="checkpassword"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("products/", include("products.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = "products"
urlpatterns = [
    path("index/", views.index, name="index"),
    path("<int:pid>/detail/", views.detail, name="detail"),
    path("create/", views.create, name="create"),
    path("<int:pid>/likey/", views.likey, name="likey"),
    path("myprodlist/", views.myprodlist, name="myprodlist"),
    path("minelist/", views.minelist, name="minelist"),
    path("<int:pid>/mine/", views.mine, name="mine"),
    path("<int:pid>/update/", views.update, name="update"),
    path("delete/", views.delete, name="delete"),
    path("buy/", views.buy, name="buy"),
    path("buylist/", views.buylist, name="buylist"),
    path("pointlist/", views.pointlist, name="pointlist"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import pre_delete
from django.dispatch import receiver
# Create your models here.

class User(AbstractUser):

    class Grades(models.TextChoices):
        BRONZE = "B", "Bronze"
        SILVER = "S", "Silver"
        GOLD = "G", "Gold"
        DIAMOND = "D", "Diamond"

    profile_pic = models.ImageField(upload_to="profile_pics/", blank=True)
    point = models.IntegerField(default=10000)
    following = models.ManyToManyField("self", symmetrical=False, blank=True, related_name="followers")
    introduce = models.TextField(blank=True)
    grade = models.CharField(max_length=1, choices=Grades.choices, default=Grades.BRONZE)

    def __str__(self):
        return f"{self.username} 님"
    
    def getpic(self):
        if self.profile_pic:
            return self.profile_pic.url
        return "/static/images/noprofile.png"

    @property
    def display_grade(self):
        if self.grade == self.Grades.BRONZE:
            return "Bronze 🥉"
        elif self.grade == self.Grades.SILVER:
            return "Silver 🥈"
        elif self.grade == self.Grades.GOLD:
            return "Gold 🥇"
        elif self.grade == self.Grades.DIAMOND:
            return "Diamond 💎"
        return self.grade
    
    class Meta:
        pass

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import authenticate
from products.models import PointHistory
from django.contrib.auth.hashers import check_password
from django.http import HttpResponseRedirect, JsonResponse
from django.utils.safestring import mark_safe
from .models import User
from django.contrib import messages
from django.utils import timezone
import json

# Create your views here.
def index(request):
    return render(request, "accounts/index.html")

def login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        userpass = request.POST.get("password")
        user = authenticate(request, username=username, password=userpass)
        if user is not None:
            if user.last_login:
                if user.last_login.date() != timezone.now().date():
                    user.point += 1000
                    user.save()
                    PointHistory.objects.create(user=user, change_amount=1000, reason="로그인 보너스")

                    message = mark_safe(f"{user.username} 님! \n오늘도 오셨군요! 추가로 <b class='add-point'>1000 point</b> 가 지급되었습니다!")
                    messages.success(request,message)
                else:
                    messages.success(request, f"{user.username} 님! 환영합니다!")
            else:
                user.point += 1000
                user.save()
                PointHistory.objects.create(user=user, change_amount=1000, reason="로그인 보너스")
                message = mark_safe(f"{user.username} 님! 환영합니다! \n저희 사이트는 하루에 한 번 로그인을 하면 <b class='add-point'>10 point</b> 가 지급되요!")
                messages.success(request, message)
            auth_login(request, user)
            return redirect("accounts:index")
        else:
            messages.error(request, "회원정보가 일치하지 않습니다. 다시 시도해주세요.") 
    return render(request, "accounts/login.html")

def logout(request):
    auth_logout(request)
    messages.success(request, "로그아웃 되었습니다. 다음에 또 뵙겠습니다!")
    return redirect("accounts:index")

def signup(request):
    if request.method == "POST":
        username = request.POST.get("username")
        userpass = request.POST.get("regpass")
        email = request.POST.get("usermail")
        profile_pic = request.FILES.get("profile_pic")
        introduce = request.POST.get("introduce")
        if checkSignup(request, username, userpass, email):
            User.objects.create_user(username=username, password=userpass, email=email, profile_pic=profile_pic, introduce=introduce)
            message = mark_safe(f"{username} 님! \n 회원가입을 축하드립니다! \n 회원가입을 축하하며 <b class='add-point'>10000 Point</b> 를 지급해드립니다! \n로그인해주세요!")
            PointHistory.objects.create(user=User.objects.get(username=username), change_amount=10000, reason="회원가입 보너스")
            messages.success(request, message)
            return redirect("accounts:login")
        else:
            messages.success(request, "회원가입에 실패하였습니다. 다시 시도해주세요.")
    return render(request, "accounts/signup.html")

def checkSignup(request, username, userpass, email):
    if User.objects.filter(username=username).exists():
        messages.error(request, "이미 존재하는 아이디입니다.")
    if User.objects.filter(email=email).exists():
        messages.error(request, "이미 존재하는 이메일입니다.")
    if len(userpass) < 8:
        messages.error(request, "비밀번호는 8자 이상으로 설정해주세요.")
    if not any(char.isdigit() for char in userpass):
        messages.error(request, "비밀번호는 숫자를 포함해야 합니다.")
    if not any(char.isalpha() for char in userpass):
        messages.error(request, "비밀번호는 문자를 포함해야 합니다.")
    if not any(char.isupper() for char in userpass):
        messages.error(request, "비밀번호는 대문자를 포함해야 합니다.")
    if not any(char.islower() for char in userpass):
        messages.error(request, "비밀번호는 소문자를 포함해야 합니다.")
    if not any(char in "!@#$%^&*()_+-=,.<>?/;:'" for char in userpass):
        messages.error(request, "비밀번호는 특수문자를 포함해야 합니다.")
    if messages.get_messages(request):
        return False
    return True

def profile(request):
    return render(request, "accounts/profile.html")       

def seller(request, name):
    user = User.objects.get(username=name)
    context = {
        "userdata" : user,
    }
    return render(request, "products/seller.html", context)

def update(request):
    if request.method == "POST":
        user = request.user
        changePic, changeComment, changePass = request.FILES.get("changePic"), request.POST.get("changeComment"), request.POST.get("changePass")
        if changePic:
            user.profile_pic.delete()
            user.profile_pic = changePic
        if changeComment:
            user.introduce = changeComment
        if changePass:
            user.set_password(changePass)
            user.save()
            messages.success(request, "비밀번호가 변경되었습니다. 다시 로그인해주세요.")
            return redirect("accounts:login")
        # 변경사항 저장
        user.save()
        messages.success(request, "변경사항이 저장되었습니다.")
    return render(request, "accounts/profile.html")

def delete(request):
    if request.method == "POST":
        request.user.profile_pic.delete()
        request.user.delete()
        auth_logout(request)
        messages.success(request, "회원탈퇴가 완료되었습니다.")
        return JsonResponse({"result": True})

def nameDuplicate(request):
    username = request.POST.get("username")
    result = User.objects.filter(username=username).exists()
    return JsonResponse({"result": result})

def mailDuplicate(request):
    email = request.POST.get("usermail")
    result = User.objects.filter(email=email).exists()
    return JsonResponse({"result": result})

def checkpassword(request):
    print(request.POST)
    password = request.POST.get("password")
    result = check_password(password, request.user.password)
    return JsonResponse({"result": result})

def follow(request, name):
    user = request.user
    target = User.objects.get(username=name)
    if user != target:
        if target in user.following.all():
            user.following.remove(target)
            messages.error(request, f"{target.username} 님을 언팔로우합니다.")
        else:
            user.following.add(target)
            messages.success(request, f"{target.username} 님을 팔로우합니다.")
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

templates/accounts/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <style>
        
        .main-image{
            width: 350px;
            height: 250px;
        }
        .moogge{
            color: rgb(52, 89, 255);
        }
        .intro{
            margin-top: 100px;
        }
        .site-intro > a{
            text-decoration: none;
            color: rgb(185, 201, 255);
        }
        .site-intro > a:hover{
            color: #e4be70;
        }
        
    </style>
    <div class="container text-center vertical intro">
        <p class="moogge-intro">반가워, 나는 <b class="moogge">뭉게</b><sup>☁️</sup>야 </p>
        <img class="main-image" src="{% static 'images/cloud.png' %}">
        {% if user.is_authenticated %}
            <p class="site-intro mt-4">
                지친 하루, 쇼핑하면서 <b class="moogge">뭉게</b>진 인상을 풀어보자~ <br>
                로그인도 했겠다, <a href="{% url 'products:index' %}">쇼핑</a>하러 가보자구!<br>
            </p>
        {% else %}
            <p class="site-intro mt-4">
                지친 하루, 쇼핑하면서 <b class="moogge">뭉게</b>진 인상을 풀어보자~ <br>
                우선 <a href="{% url 'accounts:login' %}">로그인</a>먼저 해주라구~ 름 <br>
            </p>
        {% endif %}
    </div>
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
        .login-form {
            margin-top: 100px;
            width: 50%;
            background-color: #d4e9ff;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            display: inline-block;
            border-radius: 40px;
        }
        
        .login-form input {
            width: 80%;
            height: 40px;
            margin: 15px;
            padding: 10px;
            background-color: transparent;
            border: none;
            border-radius: 5px;
            border-bottom: #c6c9cc 2px solid;
        }
        .login-form button {
            width: 80%;
            margin: 15px;
            padding: 10px;
            border: none;
            border-radius: 10px;
            background-color: #90959b5c;
            color: white;
            font-size: 20px;
        }

        .reg-form{
            width: 50%;
            display: inline-block;
            margin-top: 20px;
        }
        .reg-form button{
            width: 45%;
            margin: 15px;
            padding: 10px;
            border: none;
            border-radius: 10px;
            background-color: #90959b41;
            color: white;
            font-size: 17px;
        }
        
    </style>
    <div class="container text-center">
        <div class="login-form">
            <form action="{% url 'accounts:login' %}" class="vertical mt-4" method="POST">
                {% csrf_token %}
                <input type="text" name="username" class="first-focus" placeholder="아이디를 입력해주세요">
                <input type="password" name="password" placeholder="패스워드를 입력해주세요">
                <button type="submit">로그인</button>
            </form>
        </div>
    
        <div class="reg-form justify-content-center">
            <button class="btn btn-secondary">회원가입</button>
            <button class="btn btn-secondary">패스워드 분실</button>
        </div>
    </div>

{% endblock %}

templates/accounts/mylist.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
<style>
    .wishcon{
        margin-top: 50px;
        width: 80%;
    }

    .wishtable{
        width: 100%;
        border-collapse: collapse;
        border-spacing: 0;
        margin-top: 50px;
    }
    .wishtable tr{
        border-bottom: 1px solid #c6c9cc;
    }
    .wishtable tbody > tr:hover{
        background-color: #c6c9cc21;
    }
    .wishtable thead > tr, .wishtable thead th{
        background-color: #97999b23;
        color: white;
        font-size: 17px;
        padding: 15px;
    }
    .wishtable tbody td{
        padding: 25px;
    }

    .product-pic{
        width: 100px;
        height: 100px;
        object-fit: contain;
    }

    .protitle{
        font-size: 20px;
        color: black;
    }
    .protitle:hover{
        color: blue;
        font-weight: bold;
    }
    img:hover{
        opacity: 0.5;
    }
    .btn-myprod-cancel{
        background-color: transparent;
        border:none;
    }
    .original-price {
        text-decoration: line-through;
    }

    .sale_price {
        margin-left: 10px;
        color: red;
    }
    .avail{
        color: green;
        font-weight: bold;
    }
    .not-avail{
        color: red;
        font-weight: bold;
    }
</style>
<div class="container wishcon">
    <div class="page-subject text-center">찜 목록</div>
    <table class="wishtable text-center">
        <thead>
            <tr>
                <th scope="col">순번</th>
                <th scope="col">상품이미지</th>
                <th scope="col">상품명</th>
                <th scope="col">가격</th>
                <th scope="col">구매가능여부</th>
                <th scope="col">취소</th>
            </tr>
        </thead>
        <tbody>
            {% for p in products %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'products:detail' p.id %}"><img src="{{ p.getpic }}" class="product-pic"></a></td>
                <td><a href="{% url 'products:detail' p.id %}" class="protitle">{{ p.title }}</a></td>
                <td>{% if p.sale_price %}<sup class="original-price">{{ p.price|intcomma }}</sup><span class="sale_price">{{ p.sale_price|intcomma }}</span>{% else %}{{ p.price|intcomma }}{% endif %} points</td>
                <td>{% if p.is_avail %}
                    <span class="avail">가능</span>
                    {% else %}
                    <span class="not-avail">불가</span>
                    {% endif %}</td>
                <td>
                    <form method="post" action="{% url 'products:mylist' %}">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="{{ p.id }}">
                        <button type="submit" class="btn-myprod-cancel">❎</button>
                    </form>
                </td>
            </tr>
            
            {% empty %}
                <tr>
                    <td colspan="6">등록된 상품이 없습니다.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<script>
    
</script>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
    <style>
        .image-view{
            margin-top: 20px;
        }
        
        .signup-form {
            margin-top: 100px;
            width: 50%;
            background-color: #d4e9ff;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            display: inline-block;
            border-radius: 40px;
            align-items: center;
        }
        
        .signup-form input {
            width: 80%;
            height: 40px;
            margin: 15px;
            padding: 10px;
            background-color: transparent;
            border: none;
            border-radius: 5px;
            border-bottom: #c6c9cc 2px solid;
        }

        .signup-form button {
            width: 80%;
            margin: 15px;
            padding: 10px;
            border: none;
            border-radius: 10px;
            background-color: #90959b5c;
            color: white;
            font-size: 20px;
        }
        .not-available {
            color: red;
            font-size: 12px;
        }
        .available {
            color: green;
            font-size: 12px;
        }
        form > span{
            display: block;
            margin-top: 15px;
        }
        .introtext{
            width: 80%;
            height: 100px;
            margin: 15px;
            padding: 10px;
            background-color: transparent;
            border-top: none;
            border-radius: 5px;
            border-left: none;
            border-right: #c6c9cc 2px solid;;
            border-bottom: #c6c9cc 2px solid;
            resize: none;
        }
        #upload-photo {
            opacity: 0;
            position: absolute;
            z-index: -1;
        }
    </style>
    <div class="container text-center">
        <div class="signup-form">
            <div class="page-subject">회원가입</div>
            <form action="{% url 'accounts:signup' %}" id="signupForm" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <span id="reg-name-state"></span>
                <input type="text" name="username" class="first-focus" placeholder="아이디를 입력해주세요">
                <span id="reg-mail-state"></span>
                <input type="email" name="usermail" placeholder="이메일을 입력해주세요">
                <input type="password" name="regpass" placeholder="패스워드를 입력해주세요">
                <span id="reg-pass-state"></span>
                <input type="password" name="chkpass" placeholder="패스워드를 다시 입력해주세요">

                <label for="upload-photo" class="btn btn-secondary">프로필 사진 등록</label>
                <div class="image-view" id="image-preview">
                    <img src="{% static 'images/noprofile.png' %}" style="width:200px; height: 200px; object-fit: cover;">
                </div>
                <input type="file" id="upload-photo" name="profile_pic" style="border-bottom: none;" onchange="loadFile(this)">
                
                <textarea name="introduce" class="introtext" placeholder="자신을 소개해보세요"></textarea>
                <button type="submit">SIGNUP</button>
            </form>
        </div>
    </div>
    
    <script>
        const usernameInput = document.querySelector('input[name="username"]');
        const usermailInput = document.querySelector('input[name="usermail"]');
        const usernameState = document.querySelector('#reg-name-state');
        const passwordState = document.querySelector('#reg-pass-state');
        const usermailState = document.querySelector('#reg-mail-state');
        const userpassInput = document.querySelector('input[name="regpass"]');
        const userchkpassInput = document.querySelector('input[name="chkpass"]');
        const csrf_token = '{{ csrf_token }}';

        let usernameBool = false;
        let usermailBool = false;
        let userpassBool = false;

        usernameInput.addEventListener('keyup', function () {
            const username = usernameInput.value.trim();
            const formData = new FormData();
            formData.append('username', username);
            formData.append('csrfmiddlewaretoken', csrf_token);

            if (username.length > 4) {
                fetch('/accounts/nameDuplicate/', {
                    method: 'POST',
                    body: formData
                })
                    .then(response => response.json())
                    .then(data => {
                        if (data.result) {
                            usernameState.innerHTML = "사용중인 아이디입니다.";
                            usernameState.setAttribute('class', 'not-available');
                            usernameBool = false;
                        } else {
                            usernameState.color = "green";
                            usernameState.innerHTML = "사용가능한 아이디입니다.";
                            usernameState.setAttribute('class', 'available');
                            usernameBool = true;
                        }
                    })
                    .catch(error => console.error('Error:', error));
            } else {
                usernameState.innerHTML = "아이디는 5자리 이상으로 설정해주세요.";
                usernameState.setAttribute('class', 'not-available');
                usernameBool = false;
            }
        });
        usernameInput.addEventListener('focusout', function () {
            if (usernameBool) {
                usernameState.style.display = "none";
            }else{
                usernameState.style.display = "block";
            }
        });

        function isValidEmail(email) {
            const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
            return emailPattern.test(email);
        }

        usermailInput.addEventListener('keyup', function () {
            const usermail = usermailInput.value.trim();
            const formData = new FormData();
            formData.append('usermail', usermail);
            formData.append('csrfmiddlewaretoken', csrf_token);
            
            if (!isValidEmail(usermail)) {
                usermailState.innerHTML = "유효하지 않은 이메일 형식입니다.";
                usermailState.setAttribute('class', 'not-available');
                usermailBool = false;
            } else {
                fetch('/accounts/mailDuplicate/', {
                    method: 'POST',
                    body: formData
                })
                .then(response => response.json())
                .then(data => {
                    if (data.result) {
                        usermailState.innerHTML = "이미 가입된 이메일입니다.";
                        usermailState.setAttribute('class', 'not-available');
                        usermailBool = false;
                    } else {
                        usermailState.innerHTML = "사용가능한 이메일입니다.";
                        usermailState.setAttribute('class', 'available');
                        usermailBool = true;
                    }
                })
                .catch(error => console.error('Error:', error));
            }
        });
        usermailInput.addEventListener('focusout', function () {
            if (usermailBool) {
                usermailState.style.display = "none";
            }else{
                usermailState.style.display = "block";
            }
        });


        function validatePassword(password) {
            if (password.length < 8) {
                return "패스워드는 최소 8자리 이상이어야 합니다.";
            }
            const hasUpperCase = /[A-Z]/.test(password);
            const hasLowerCase = /[a-z]/.test(password);
            const hasDigit = /\d/.test(password);
            const hasSpecial = /[ `!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?~]/.test(password); 
            if (!(hasUpperCase && hasLowerCase && hasDigit && hasSpecial)) {
                return "패스워드는 대문자, 소문자, 숫자, 특수 문자를 모두 포함해야 합니다.";
            }
            return "유효한 패스워드입니다.";
        }

        userpassInput.addEventListener('keyup', function () {
            const password = userpassInput.value.trim();
            const passwordState = document.querySelector('#reg-pass-state');
            passwordState.innerHTML = validatePassword(password);
            if (passwordState.innerHTML === "유효한 패스워드입니다.") {
                passwordState.setAttribute('class', 'available');
                userpassBool = true;
            } else {
                passwordState.setAttribute('class', 'not-available');
                userpassBool = false;
            }
        });

        userpassInput.addEventListener('focusout', function () {
            if (userpassBool) {
                passwordState.style.display = "none";
            }else{
                passwordState.style.display = "block";
            }
        });

        userchkpassInput.addEventListener('keyup', function () {
            const password = userpassInput.value.trim();
            const chkpassword = userchkpassInput.value.trim();
            passwordState.style.display = "block";
            if (password === chkpassword) {
                passwordState.innerHTML = "패스워드가 일치합니다.";
                passwordState.setAttribute('class', 'available');
                userpassBool = true;
            } else {
                passwordState.innerHTML = "패스워드가 일치하지 않습니다.";
                passwordState.setAttribute('class', 'not-available');
                userpassBool = false;
            }
        });

        userchkpassInput.addEventListener('focusout', function () {
            if (userpassBool) {
                passwordState.style.display = "none";
            }else{
                passwordState.style.display = "block";
            }
        });

        function signupCheck() {
            if (!usernameBool) {
                alert("입력하신 아이디를 확인해주세요");
            } else if (!userpassBool) {
                alert("입력하신 패스워드를 확인해주세요");
            } else if (!usermailBool) {
                alert("입력하신 이메일을 확인해주세요");
            } else {
                document.getElementById("signupForm").submit();
            }
        }
        
    

    </script>
{% endblock %}