accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("index/", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("profile/", views.profile, name="profile"),
    path("seller/<str:name>/", views.seller, name="seller"),
    path("follow/<str:name>/", views.follow, name="follow"),
    path("update/", views.update, name="update"),
    path("delete/", views.delete, name="delete"),
    path("nameDuplicate/", views.nameDuplicate, name="nameDuplicate"),
    path("mailDuplicate/", views.mailDuplicate, name="mailDuplicate"),
    path("checkpassword/", views.checkpassword, name="checkpassword"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("products/", include("products.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = "products"
urlpatterns = [
    path("index/", views.index, name="index"),
    path("<int:pid>/detail/", views.detail, name="detail"),
    path("create/", views.create, name="create"),
    path("<int:pid>/likey/", views.likey, name="likey"),
    path("myprodlist/", views.myprodlist, name="myprodlist"),
    path("minelist/", views.minelist, name="minelist"),
    path("<int:pid>/mine/", views.mine, name="mine"),
    path("<int:pid>/update/", views.update, name="update"),
    path("delete/", views.delete, name="delete"),
    path("buy/", views.buy, name="buy"),
    path("buylist/", views.buylist, name="buylist"),
    path("pointlist/", views.pointlist, name="pointlist"),
]

products/models.py
from django.db import models
from accounts.models import User
from django.db.models.signals import pre_delete
from django.dispatch import receiver


# Create your models here.
class Products(models.Model):
    title = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.TextField()
    image = models.ImageField(upload_to="product_images/")
    stock = models.IntegerField(default=0)
    sale_price = models.IntegerField(default=0)
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name="products")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    hits = models.IntegerField(default=0)
    likey = models.ManyToManyField(User, related_name="likey", blank=True)
    score = models.FloatField(default=0)
    display_price = models.IntegerField(default=0)
    wishuser = models.ManyToManyField(User, related_name="wishprod", blank=True)


    def __str__(self):
        return f"{self.title} - {self.seller.username}"
    
    def getpic(self):
        if self.image:
            return self.image.url
        return "/static/images/noprod.png"
    
    def getstock(self):
        if self.stock == 0:
            return "품절"
        elif self.stock < 10:
            return f"품절 임박 ({self.stock} left)"
        return "재고 있음"
    
    def is_avail(self):
        if self.stock > 0:
            return True
        return False
    
    class Meta:
        pass




class HashTag(models.Model):
    name = models.CharField(max_length=50)
    products = models.ManyToManyField(Products, related_name="hashtags")

    def __str__(self):
        return self.name

    class Meta:
        pass

@receiver(pre_delete, sender=Products)
def remove_unused_hashtags(sender, instance, **kwargs):
    hashtags = instance.hashtags.all()
    for hashtag in hashtags:
        if hashtag.products.count() <= 1:
            hashtag.delete()


class BuyList(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE, related_name="buylist")
    buyer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="buylist")
    quantity = models.IntegerField()
    priced = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.product.title} - {self.buyer.username} - {self.quantity}"

    class Meta:
        pass


class PointHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="pointhistory")
    change_amount = models.IntegerField()
    reason = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.change_amount} - {self.reason}"

        

products/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import Products, HashTag, BuyList, PointHistory
from django.core.paginator import Paginator
from django.db.models import Count
from django.db.models import Q
from django.contrib import messages

# Create your views here.
def index(request):
    page = request.GET.get("page", 1)
    cate = request.GET.get("cate", "")
    sort = request.GET.get("sort","")
    keyword = request.GET.get("keyword", "")
    stockOut = request.GET.get("stockOut", False)
    saleProd = request.GET.get("saleProd", False)

    if keyword:
        if cate == "title":
            products = Products.objects.filter(title__contains=keyword)
        elif cate == "seller":
            products = Products.objects.filter(seller__username=keyword)
        elif cate == "hashtag":
            products = Products.objects.filter(hashtags__name=keyword)
    else:   
        products = Products.objects.all()

    if stockOut == 'false':
        products = products.filter(~Q(stock=0))
    if saleProd == 'true':
        products = products.filter(~Q(sale_price=0))

    
    if not sort or sort == "new":
        products = products.order_by("-created_at")
    elif sort == "cheap":
        products = products.order_by("display_price")
    elif sort == "expensive":
        products = products.order_by("-display_price")
    elif sort == "hits":
        products = products.order_by("-hits")
    elif sort == "likey":
        products = products.annotate(likey_count=Count('likey')).order_by('-likey_count')
    elif sort == "score":
        products = products.order_by("-score")
        
    pag = Paginator(products, 4)
    obj = pag.get_page(page)
    exposedPost = int(page) * 4
    print(exposedPost)
    if exposedPost > obj.paginator.count:
        exposedPost = obj.paginator.count

    context = {
        "obj": obj,
        "page": page,
        "cate": cate,
        "keyword": keyword,
        "sort": sort,
        "stockOut": stockOut,
        "saleProd": saleProd,
        "exposedPost": exposedPost,
    }
    return render(request, "products/index.html", context)

def detail(request, pid):
    product = Products.objects.get(id=pid)
    if request.META.get('HTTP_REFERER') and not f"/{pid}/detail/" in request.META.get('HTTP_REFERER'):
        product.hits += 1
        product.save()
    context = {
        "p": product,
    }
    return render(request, "products/detail.html", context)

def create(request):
    if request.method == "POST":
        title = request.POST.get("productTitle")
        price = request.POST.get("productPrice")
        sale_price = request.POST.get("productSalePrice")
        description = request.POST.get("productDesc")
        image = request.FILES.get("productImage")
        stock = request.POST.get("productStock")
        hashtags = request.POST.getlist("productHashtag")  
        seller = request.user
        display_price = price
        if sale_price:
            display_price = sale_price
        else:
            sale_price = 0
        product = Products(title=title, price=price, stock=stock, sale_price=sale_price, display_price=display_price, description=description, image=image, seller=seller)
        
        product.save()

        for tag in hashtags:
            tag = tag.split()[0].replace("#", "")
            if not HashTag.objects.filter(name=tag).exists():
                hashtag = HashTag(name=tag)
                hashtag.save()
            else:
                hashtag = HashTag.objects.get(name=tag)
            product.hashtags.add(hashtag)
        messages.success(request, "상품이 등록되었습니다.")
        return redirect('products:index')
    return render(request, "products/create.html")

def likey(request, pid):
    p = Products.objects.get(id=pid)
    user = request.user
    if user in p.likey.all():
        p.likey.remove(user)
        messages.error(request, "좋아요를 취소합니다.")
    else:
        p.likey.add(user)
        messages.success(request, "좋아요를 눌렀습니다.")
    return redirect("products:detail", pid)

def mine(request, pid):
    p = Products.objects.get(id=pid)
    user = request.user
    if p in user.wishprod.all():
        user.wishprod.remove(p)
        messages.error(request, "찜을 취소합니다.")
    else:
        user.wishprod.add(p)
        messages.success(request, "찜을 눌렀습니다.")
    return redirect(request.META.get('HTTP_REFERER'))

def minelist(request):
    user = request.user
    products = user.wishprod.all()
    context = {
        "products": products,
    }
    return render(request, "products/minelist.html", context)

def update(request, pid):
    p = Products.objects.get(id=pid)
    if request.method == "POST":
        title = request.POST.get("productTitle")
        price = request.POST.get("productPrice")
        sale_price = request.POST.get("productSalePrice")
        description = request.POST.get("productDesc")
        image = request.FILES.get("productImage")
        stock = request.POST.get("productStock")
        hashtags = request.POST.getlist("productHashtag")
        pre_page = request.POST.get("prepage", "products:index")
        display_price = price
        if sale_price:
            display_price = sale_price
            p.sale_price = sale_price
        else:
            p.sale_price = 0
        p.title = title
        p.price = price
        p.description = description
        p.display_price = display_price
        p.stock = stock
        if image:
            p.image.delete()
            p.image = image
        p.save()
        p.hashtags.clear()
        for tag in hashtags:
            tag = tag.split()[0].replace("#", "")
            if not HashTag.objects.filter(name=tag).exists():
                hashtag = HashTag(name=tag)
                hashtag.save()
            else:
                hashtag = HashTag.objects.get(name=tag)
            p.hashtags.add(hashtag)
        messages.success(request, "상품이 수정되었습니다.")
        return redirect(pre_page)
    context = {
        "p": p,
        "prepage":request.META.get('HTTP_REFERER')
    }
    return render(request, "products/update.html", context)


def delete(request):
    if request.method == "POST":
        pid = request.POST.get("product_id")
        print(pid)
        p = Products.objects.get(id=pid)
        if p.seller == request.user:
            p.image.delete()
            p.delete()
            messages.error(request, "상품이 삭제되었습니다.")
        return JsonResponse({"result": True})

def myprodlist(request):
    user = request.user
    products = user.products.all()
    context = {
        "products": products,
    }
    return render(request, "products/myprodlist.html", context)

def buy(request):
    if request.method == "POST":
        pids = request.POST.getlist("product_id")
        quantities = request.POST.getlist("quantity")
        total = 0
        for pid, quantity in zip(pids, quantities):
            product = Products.objects.get(id=pid)
            quantity = int(quantity)
            total += product.display_price * quantity
        if request.user.point < total:
            messages.error(request, "포인트가 부족합니다.")
            return redirect("products:buy")
        
        for pid, quantity in zip(pids, quantities):
            product = Products.objects.get(id=pid)
            quantity = int(quantity)
            BuyList(product=product, priced=product.display_price, buyer=request.user, quantity=quantity).save()
            PointHistory(user=request.user, change_amount=-(product.display_price * quantity), reason=f"{product.title} {quantity} 개 구매").save()
            product.stock -= quantity
            product.save()
            product.seller.point += product.display_price * quantity
            PointHistory(user=product.seller, change_amount=product.display_price * quantity, reason=f"{product.title} {quantity} 개 판매").save()
            product.seller.save()
        
        request.user.point -= total
        request.user.save()
        messages.success(request, "구매가 완료되었습니다.")
        return redirect("products:buylist")
    
    product_id = request.GET.get("product_id")
    if product_id:
        context = {
            "products": [Products.objects.get(id=product_id)]
        }
    else:
        context = {
            "products": request.user.wishprod.all()
        }
    return render(request, "products/buy.html", context)
    
def buylist(request):
    user = request.user
    products = user.buylist.all()
    products = products.order_by("-created_at")
    context = {
        "products": products,
    }
    return render(request, "products/buylist.html", context)

def pointlist(request):
    user = request.user
    points = user.pointhistory.all()
    points = points.order_by("-created_at")
    context = {
        "points": points,
    }
    return render(request, "products/pointlist.html", context)

templates/products/detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% load mathfilters %}
{% block content %}
<style>
    .container {
        margin-top: 50px;
        width: 80%;
    }

    .badge-red {
        background-color: red;
        color: white;
    }

    .badge-orange {
        background-color: orange;
        color: white;
    }

    .badge-green {
        background-color: green;
        color: white;
    }

    .original-price {
        text-decoration: line-through;
    }

    .sale_price {
        margin-left: 10px;
        color: red;
    }
    .profile-icon{
        width: 30px;
        height: 30px;
        border-radius: 50%;
        margin-right: 10px;
        object-fit: cover;
    }
    .info-table td{
        font-size: 20px;
        padding-bottom: 15px;
    }
    .info-table td:nth-child(1){
        font-weight: bolder;
        font-size: 24px;
        color: white;
        width: 20%;
        text-shadow: 0px 0px 4px #0048ff;
    }
    .info-table td:nth-child(2){
        padding-left: 40px;
    }
    .info-table{
        background-color: transparent;
        text-align: left;
        padding: 20px;
    }
    .product-pic{
        width: 100%;
    }
    .info-div{
        margin-top: 20px;
    }
    .rating{
        color: gold;
        text-shadow: 0px 0px 6px skyblue;
    }
    .score-span{
        margin-left: 20px;
        font-size: 14px;
    }
    .likey-button{
        background-color: transparent;
        border: none;
    }
    .like-div span{
        margin-left: 20px;
        font-size: 18px;
    }
    .cusdropdown {
        position: relative;
        display: inline-block;
        font-size: 14px;
    }
    .cusdropdown span{
        font-size: 20px;
    }
    .cusdropdown-content {
        display: none;
        position: absolute;
        background-color: #cdd6d5;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(193, 194, 246, 0.601);
        z-index: 1;
    }
    .cusdropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
    }
    .cusdropdown-content a:hover {
        background-color: #f1f1f1;
    }
    .cusdropdown:hover .cusdropdown-content {
        display: block;
    }
    .productBtn{
        text-align: end;
    }
    .productBtn a{
        margin-top: 20px;
        padding-left: 20px;
        padding-right: 20px;
        margin-left: 20px;
        font-size: 18px;
    }
    .btn-cart{
        background-color: #94ba8c;
        color: white;
    }
    .btn-myprod{
        background-color: #aec892;
        color: white;
    }
    .btn-myprod-cancel{
        background-color: #ffc3c3;
        color: white;
    }
    .btn-buy{
        background-color: #f7d794;
        color: white;
    }
    .btn-back{
        background-color: #c6c9cc;
        color: white;
    }
    .hashtag{
        background-color: #a1bbf7;
        color: white;
        padding: 5px;
        margin-right: 5px;
        margin-bottom: 10px;
    }
    .udsection{
        margin-top: 20px;
    }
    .udsection button{
        margin-left: 10px
    }

</style>
<div class="container text-center">
    <div class="text-end">
        {% for i in p.hashtags.all %}
            <span class="badge hashtag"># {{ i.name }}</span>
        {% endfor %}
    </div>
    <div class="row">
        <div class="col-8" style="margin: auto;">
            <table class="info-table">
                <tbody>
                    <tr>
                        <td>상품명</td>
                        <td>{{ p.title }}</td>
                    </tr>
                    <tr>
                        <td>판매자</td>
                        <td>
                            <img src="{{ p.seller.getpic }}" class="profile-icon">
                            <div class="cusdropdown">
                                <span>{{ p.seller.username }}</span>
                                <div class="cusdropdown-content">
                                    <a href="{% url 'accounts:seller' p.seller.username %}">프로필보기</a>
                                    {% if user != p.seller %}
                                        {% if p.seller in user.following.all %}
                                            <a href="{% url 'accounts:follow' p.seller.username %}">팔로우취소</a>
                                        {% else %}
                                            <a href="{% url 'accounts:follow' p.seller.username %}">팔로우하기</a>
                                        {% endif %}
                                    {% endif %}
                                    <a href="{% url 'products:index' %}?cate=seller&keyword={{p.seller.username}}&stockOut=false">등록한 제품보기</a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>가격</td>
                        <td>
                            {% if p.sale_price %}
                                <sup><span class="original-price">{{ p.price|intcomma }} Points</span></sup>
                                <span class="sale_price">{{ p.sale_price|intcomma }} Points</span>
                            {% else %}
                                {{ p.price|intcomma }} Points
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>재고</td>
                        <td>{{ p.stock }}</td>
                    </tr>
                    <tr>
                        <td>제품설명</td>
                        <td>{{ p.description }}</td>
                    </tr>
                </tbody>
            </table>    
        </div>

        <div class="col-4" style="margin: auto;">
            <img src="{{ p.getpic }}" class="product-pic" alt="...">
        </div>
    </div>


    <div class="info-div text-end">
        <div class="product-score">
            <div>
                <span class="rating">
                    {% for i in "12345" %}
                        {% if i|add:"0" <= p.score %}
                            <span class="full">&#9733;</span>
                        {% elif p.score|sub:i|add:"0" < 0.5 %}
                            <span class="full">&#9734;</span>
                        {% else %}
                            <span class="half">&#9734;</span>
                        {% endif %}
                    {% endfor %}
                </span>
                <span class="score-span">구매 만족도 <b>{{ p.score }}</b></span>
            </div>
        </div>
        <div class="product-info">
            <span>{{ p.created_at|date:'Y년 m월 d일' }}</span>
        </div>

        <div class="like-div">
            <span><a href="{% url 'products:likey' p.id %}"><button class="likey-button">{% if user in p.likey.all %}❤️{% else %}♡{% endif %}</button></a> {{ p.likey.count }}</span>
            <span> 👀 {{ p.hits }}</span>
        </div>
    </div>

    {% if user == p.seller %}
        <div class="text-end udsection">
            <a href="{% url 'products:update' p.id %}" class="btn btn-moong">게시글 수정</a>
            <button type="button" onclick="checkRemove()" class="btn btn-moong">게시글 삭제</button>
        </div>
    {% endif %}


    <input type="hidden" name="product_id" value="{{ p.id }}">
    <div class="productBtn">
        {% if user in p.wishuser.all %}
            <a href="{% url 'products:mine' p.id %}" class="btn btn-myprod-cancel">찜취소</a>
        {% else %}
            <a href="{% url 'products:mine' p.id %}" class="btn btn-myprod">찜하기</a>
        {% endif %}
        {% if p.seller != user %}
            <a href="{% url 'products:buy' %}?product_id={{ p.id }}" class="btn btn-buy">구매하기</a>
        {% endif %}
        <a class="btn btn-back" onclick="goBackPage()">뒤로가기</a>
    </div>
    

</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>

<script>
    // 시간을 ISO 8601 형식으로 변환하여 반환
    function parseDate(dateString) {
        const date = moment(dateString, "MMMM D, YYYY, h:mm a");
        return date.toISOString();
    }

    function timeSince(date) {
        const seconds = Math.floor((new Date() - new Date(date)) / 1000);
        let interval = Math.floor(seconds / 31536000);

        if (interval >= 1) {
            return interval + " 년 전";
        }
        interval = Math.floor(seconds / 2592000);
        if (interval >= 1) {
            return interval + " 개월 전";
        }
        interval = Math.floor(seconds / 86400);
        if (interval >= 1) {
            return interval + " 일 전";
        }
        interval = Math.floor(seconds / 3600);
        if (interval >= 1) {
            return interval + " 시간 전";
        }
        interval = Math.floor(seconds / 60);
        if (interval >= 1) {
            return interval + " 분 전";
        }
        return Math.floor(seconds) + " 초 전";
    }

    const createTimeElements = document.querySelectorAll('.createTime');
    createTimeElements.forEach(function (element) {
        const createdTime = element.getAttribute('data-created-at');
        const isoDateString = parseDate(createdTime);
        element.textContent = timeSince(isoDateString);
    });

    function goBackPage(){
        window.history.back();
    }

    function checkRemove(){
        const formData = new FormData();
        formData.append('csrfmiddlewaretoken', '{{ csrf_token }}');
        formData.append('product_id', '{{ p.id }}');

        if(confirm("정말 삭제하시겠습니까?")){
            fetch("{% url 'products:delete' %}", {
                method: 'POST',
                body: formData
            }).then(response => response.json())
            .then(data => {
                if(data.result == true){
                    location.href = "{% url 'products:index' %}?stockOut=false";
                }
            });
        };
    }
</script>

{% endblock %}

templates/products/minelist.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block content %}
<style>
    .product-pic{
        width: 100px;
        height: 100px;
        object-fit: contain;
    }

    .protitle{
        font-size: 20px;
        color: black;
    }
    .protitle:hover{
        color: blue;
        font-weight: bold;
    }
    img:hover{
        opacity: 0.5;
    }
    .btn-myprod-cancel{
        background-color: transparent;
        border:none;
    }
    .original-price {
        text-decoration: line-through;
    }

    .sale_price {
        margin-left: 10px;
        color: red;
    }
    .avail{
        color: green;
        font-weight: bold;
    }
    .not-avail{
        color: red;
        font-weight: bold;
    }
    .d-icon{
        width: 25px;
        height: 25px;
        object-fit: contain;
    }
</style>
<div class="container customcon">
    <div class="page-subject text-center">찜 목록</div>
    <table class="customtable text-center">
        <thead>
            <tr>
                <th scope="col">순번</th>
                <th scope="col">상품이미지</th>
                <th scope="col">상품명</th>
                <th scope="col">가격</th>
                <th scope="col">재고유무</th>
                <th scope="col">취소</th>
            </tr>
        </thead>
        <tbody>
            {% for p in products %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'products:detail' p.id %}"><img src="{{ p.getpic }}" class="product-pic"></a></td>
                <td><a href="{% url 'products:detail' p.id %}" class="protitle">{{ p.title }}</a></td>
                <td>{% if p.sale_price %}<sup class="original-price">{{ p.price|intcomma }}</sup><span class="sale_price">{{ p.sale_price|intcomma }}</span>{% else %}{{ p.price|intcomma }}{% endif %} points</td>
                <td>{% if p.is_avail %}
                    <span class="avail">있음</span>
                    {% else %}
                    <span class="not-avail">없음</span>
                    {% endif %}</td>
                <td>
                    <a href="{% url 'products:mine' p.id %}" class="btn-myprod-cancel"><img src="{% static 'images/delete.png' %}" class="d-icon"></a>
                </td>
            </tr>
            
            {% empty %}
                <tr>
                    <td colspan="6">등록된 상품이 없습니다.</td>
                </tr>
            {% endfor %}
            {% if products %}
                <tr>
                    <td colspan="6">
                        <a href="{% url 'products:buy' %}" class="btn btn-moong">결제 페이지 이동</a>
                    </td>
                </tr>
            {% endif %}
        </tbody>
    </table>
</div>
<script>
    
</script>
{% endblock %}

templates/products/myprodlist.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block content %} 
<style>
    .product-pic{
        width: 100px;
        height: 100px;
        object-fit: contain;
    }

    .protitle{
        font-size: 20px;
        color: black;
    }
    .protitle:hover{
        color: blue;
        font-weight: bold;
    }
    img:hover{
        opacity: 0.5;
    }
    .btn-myprod-cancel{
        background-color: transparent;
        border:none;
    }
    .original-price {
        text-decoration: line-through;
    }

    .sale_price {
        margin-left: 10px;
        color: red;
    }
    .avail{
        color: green;
        font-weight: bold;
    }
    .not-avail{
        color: red;
        font-weight: bold;
    }
    .ud-icon{
        width: 20px;
        height: 20px;
    }
</style>
<div class="container customcon">
    <div class="page-subject text-center">상품관리</div>
    <table class="customtable text-center">
        <thead>
            <tr>
                <th scope="col">순번</th>
                <th scope="col">상품이미지</th>
                <th scope="col">상품명</th>
                <th scope="col">조회수</th>
                <th scope="col">좋아요</th>
                <th scope="col">수정</th>
                <th scope="col">삭제</th>
            </tr>
        </thead>
        <tbody>
            {% for p in products %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'products:detail' p.id %}"><img src="{{ p.getpic }}" class="product-pic"></a></td>
                <td><a href="{% url 'products:detail' p.id %}" class="protitle">{{ p.title }}</a></td>
                <td>{{ p.hits }}</td>
                <td>{{ p.likey.count }}</td>
                <td>
                    <a href="{% url 'products:update' p.id %}"><img src="{% static 'images/write.png' %}" class="ud-icon"></a>
                </td>
                <td>
                    <a onclick="checkRemove(this)" class="product_id" pid="{{ p.id }}"><img src="{% static 'images/delete.png' %}" class="ud-icon"></a>
                </td>
            </tr>
            
            {% empty %}
                <tr>
                    <td colspan="7">등록하신 상품이 없습니다.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<script>
    function checkRemove(e){
        const formData = new FormData();
        const pid = e.getAttribute('pid');
        formData.append('csrfmiddlewaretoken', '{{ csrf_token }}');
        formData.append('product_id', pid);

        if(confirm("정말 삭제하시겠습니까?")){
            fetch("{% url 'products:delete' %}", {
                method: 'POST',
                body: formData
            }).then(response => response.json())
            .then(data => {
                if(data.result == true){
                    window.location.reload();
                }
            });
        };
    }
</script>
{% endblock %}